ALTER SESSION SET "_ORACLE_SCRIPT"=true;
BEGIN
   EXECUTE IMMEDIATE 'DROP USER myDB CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN
         RAISE;
      END IF;
END;
/
CREATE USER myDB IDENTIFIED BY "Aa@102030";
GRANT ALL PRIVILEGES TO myDB;
GRANT CONNECT, RESOURCE, DBA TO myDB;
EXIT;
