spring.application.name=Maged System
spring.profiles.active=oracle

# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=myDB
spring.datasource.password=Aa@102030
spring.jpa.properties.hibernate.default_schema=MYDB
# Server Configuration
server.port=8081

# Hibernate settings to auto-create tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

secretejwtString=Walidovich@01113283299Walidovich@01113283299
